# 準備と目的

## 目的

Pytorchの機能を一通りさらっていく

## 準備

In [2]:
from __future__ import print_function
import torch

# 関数の説明

`.empty()`メソッドを使うことで、初期化されていない指定された大きさの配列を作成する。

In [8]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0653e-38, 7.3470e-39],
        [8.9082e-39, 1.0653e-38, 9.0919e-39],
        [4.4082e-39, 4.1327e-39, 3.6735e-39],
        [1.1112e-38, 1.0194e-38, 9.0919e-39],
        [3.7654e-39, 1.0010e-38, 1.0102e-38]])


`.rand()`メソッドを使うことで、乱数で初期化された指定された大きさの配列を作成する。

In [9]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9092, 0.0338, 0.4397],
        [0.5261, 0.5697, 0.7667],
        [0.0852, 0.4660, 0.2752],
        [0.1833, 0.0591, 0.0791],
        [0.7488, 0.5474, 0.9947]])


`.zeros()`メソッドを使うことで、0で初期化された指定された大きさの配列を作成する。(dtype= で0の型を指定する事ができる。指定なしだとfloat32)

In [19]:
x = torch.zeros(5, 3, dtype=torch.int32)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.int32


データをリストで初期化する

In [20]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


すでに存在しているtensorを使用して新しいtensorを作成することができる。

In [22]:
x = x.new_ones(5, 3, dtype=torch.double) # nwe * methods take in size
print(x)

x = torch.rand_like(x, dtype=torch.float) # override dtype!
print(x)                                  # result has the same size


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.8135, 0.6519, 0.7217],
        [0.4701, 0.3534, 0.2132],
        [0.7918, 0.7018, 0.3526],
        [0.0667, 0.3094, 0.9815],
        [0.0324, 0.4666, 0.8763]])


`x.size()`メソッドを用いて配列の大きさを確認することができる。

In [24]:
print(x.size())

torch.Size([5, 3])


足し算の例

In [26]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.7912, 1.5788, 1.3500],
        [0.8933, 0.7242, 0.8568],
        [1.4016, 1.6957, 0.4560],
        [0.2976, 1.1255, 1.4286],
        [0.3883, 1.1226, 1.7449]])


In [27]:
print(torch.add(x, y))

tensor([[1.7912, 1.5788, 1.3500],
        [0.8933, 0.7242, 0.8568],
        [1.4016, 1.6957, 0.4560],
        [0.2976, 1.1255, 1.4286],
        [0.3883, 1.1226, 1.7449]])


In [28]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.7912, 1.5788, 1.3500],
        [0.8933, 0.7242, 0.8568],
        [1.4016, 1.6957, 0.4560],
        [0.2976, 1.1255, 1.4286],
        [0.3883, 1.1226, 1.7449]])


In [29]:
y.add(x)
print(y)

tensor([[0.9778, 0.9269, 0.6283],
        [0.4232, 0.3708, 0.6436],
        [0.6099, 0.9938, 0.1033],
        [0.2309, 0.8161, 0.4471],
        [0.3558, 0.6560, 0.8686]])


スライスを使用することができる。

In [30]:
print(x[:, 1])

tensor([0.6519, 0.3534, 0.7018, 0.3094, 0.4666])


配列の形をリサイズしたい場合は`.view()`メソッドを利用する。

In [32]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


tensorの中身をPythonの値として使用するときは`.item()`メソッドを用いる。(これは)

In [39]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2534])
-0.25340279936790466


In [38]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [41]:
# tensor -> numpy
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [43]:
# addメソッドを使うことで内部の要素にすべて1を足すことができる。
# この時、インスタンスは保持されるのでa内のnumpy配列を参照しているbの内部も変更される。
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [46]:
import numpy as np
a = np.ones(5)
# numpy→torch
# この時numpy配列aの内部要素が変更されるとtensorの内部要素も変更される
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Cudaの設定はしていないのでこれは出ませんね

In [48]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    
    print(z)
    print(z.to('cpu', torch.double))

終わり